# pytest.ini
[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
    --strict-markers
    -p no:cacheprovider

markers =
    unit: Pruebas unitarias
    integration: Pruebas de integración
    slow: Pruebas lentas
    smoke: Pruebas rápidas de humo